package NewLanguage.generator.VerifiableFunctionCall;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.IVisitor;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static boolean baseMappingRule_Condition_4686410186993656934(final BaseMappingRuleContext _context) {
    return SNodeOperations.getConceptDeclaration(SLinkOperations.getTarget(_context.getNode(), "left", true)) == SConceptOperations.findConceptDeclaration("com.mbeddr.core.pointers.structure.StringLiteral") && SNodeOperations.getConceptDeclaration(SLinkOperations.getTarget(_context.getNode(), "right", true)) == SConceptOperations.findConceptDeclaration("com.mbeddr.core.pointers.structure.StringLiteral");
  }

  public static SNode sourceNodeQuery_6563710535926535333(final SourceSubstituteMacroNodeContext _context) {
    int i = 0;
    for (SNode par : ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "fcontract", false), "preconditions", true), "ParameterRange", true))) {
      SLinkOperations.setTarget(par, "value", SNodeOperations.copyNode(ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "fcall", false), "actuals", true)).getElement(i++)), true);
    }
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "fcontract", false), "preconditions", true);
  }

  public static SNode sourceNodeQuery_2361184900199593421(final SourceSubstituteMacroNodeContext _context) {
    SNode res = SNodeOperations.copyNode(SLinkOperations.getTarget(_context.getNode(), "ConditionExp", true));
    ListSequence.fromList(SNodeOperations.getDescendants(res, "NewLanguage.structure.ArgReference", false, new String[]{})).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        SNodeOperations.replaceWithAnother(it, SNodeOperations.copyNode(SLinkOperations.getTarget(_context.getNode(), "value", true)));
      }
    });
    return res;
  }

  public static SNode sourceNodeQuery_4686410186993715618(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "left", true);
  }

  public static SNode sourceNodeQuery_4686410186993737849(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "right", true);
  }
}
