package NewLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class ReturnValue_Constraints extends BaseConstraintsDescriptor {
  public ReturnValue_Constraints() {
    super("NewLanguage.structure.ReturnValue");
  }
}
