package NewLanguage.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.intentions.IntentionsManager;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("902ada2b-dddc-4d40-9436-e13ab6ba878d(NewLanguage)"), PersistenceFacade.getInstance().createModelReference("r:7333a1b7-8a8d-4366-b9c4-2eba12a838c1(NewLanguage.intentions)"));
  }

  public void init() {
    IntentionsManager.getInstance().registerIntentionFactory(new ConnectToFunction_Intention());
  }
}
