package NewLanguage.textGen;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.IVisitor;

public class GeneratorAssistant {
  public static SNode replaceIt(SNode pr, final SNode exp) {
    SNode res = SNodeOperations.copyNode(SLinkOperations.getTarget(pr, "ConditionExp", true));
    ListSequence.fromList(SNodeOperations.getDescendants(res, "NewLanguage.structure.ArgReference", false, new String[]{})).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        SNodeOperations.replaceWithAnother(it, SNodeOperations.copyNode(exp));
      }
    });
    return res;
  }
}
