package NewLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Preconditions_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    {
      Iterable<SNode> collection = SLinkOperations.getTargets(node, "ParameterRange", true);
      for (SNode item : collection) {
        appendNode(item);
      }
    }
  }
}
