package NewLanguage.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.Statement_BehaviorDescriptor;

public class CheckFunction_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public CheckFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.CheckFunction";
  }
}
