package NewLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Dependency_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Dependency_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.Dependency";
  }
}
