package NewLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ParameterSideEffect_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ParameterSideEffect_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.ParameterSideEffect";
  }
}
