package NewLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ParameterRange_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ParameterRange_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.ParameterRange";
  }
}
