package NewLanguage.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class ReturnValue_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "name", "RValue");
  }
}
