package NewLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ReturnValueRange_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ReturnValueRange_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.ReturnValueRange";
  }
}
