package NewLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.NodeAttribute_BehaviorDescriptor;

public class VerifiableFunctionCallCheckAttribute_BehaviorDescriptor extends NodeAttribute_BehaviorDescriptor {
  public VerifiableFunctionCallCheckAttribute_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.VerifiableFunctionCallCheckAttribute";
  }
}
