package NewLanguage.behavior;

/*Generated by MPS */

import com.mbeddr.core.modules.behavior.FunctionCall_BehaviorDescriptor;

public class VerifiableFunctionCall_BehaviorDescriptor extends FunctionCall_BehaviorDescriptor {
  public VerifiableFunctionCall_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.VerifiableFunctionCall";
  }
}
